# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop

minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.17.2

# Mod Properties
mod_version=1.0.5
maven_group=cybercat5555.faunus
archives_base_name=faunus

# Dependencies
fabric_version=0.116.5+1.21.1
geckolib_version=4.7.6
smart_brain_lib_version=1.16.10
trinkets_version=3.10.0